apiVersion: openobserve.ai/v1alpha1
kind: OpenObserveAlert
metadata:
  name: simple-log-alert
  namespace: o2operator
spec:
  configRef:
    name: openobserve-main
    namespace: o2operator

  name: "simple_log_alert"
  streamName: "default"
  streamType: "logs"
  enabled: true

  queryCondition:
    type: "custom"
    conditions: null
    # conditions:
    #   or:
    #     - column: job
    #       operator: ">"
    #       value: "11"
    #       ignore_case: false
    #     - or:
    #         - column: level
    #           operator: "="
    #           value: "111"
    #           ignore_case: true
    #         - column: log
    #           operator: "="
    #           value: "122"
    #           ignore_case: true

  triggerCondition:
    frequency: 5
    frequencyType: "minutes"
    period: 10
    threshold: 10
    operator: ">="

  destinations:
    - "test-o2-alerts"