apiVersion: openobserve.ai/v1alpha1
kind: OpenObserveAlert
metadata:
  name: minimal-alert
  namespace: default
spec:
  configRef:
    name: openobserve-config       #dont forget to change this to your OpenObserveConfig

  name: "minimal_alert"

  queryCondition:
    type: "custom"
    conditions:
      or:
        - column: job
          operator: ">"
          value: "11"
          ignore_case: false
        - or:
            - column: level
              operator: "="
              value: "111"
              ignore_case: true
            - column: log
              operator: "="
              value: "122"
              ignore_case: true

  triggerCondition:
    frequency: 5
    frequencyType: "minutes"
    period: 10
    threshold: 1
    operator: ">="

  destinations:
    - "default_channel"