apiVersion: openobserve.ai/v1alpha1
kind: OpenObserveAlert
metadata:
  name: sql-alert
  namespace: o2operator
spec:
  configRef:
    name: openobserve-main       #dont forget to change this to your OpenObserveConfig
    namespace: o2operator

  name: "sql_query_alert"
  streamName: "default"
  streamType: "logs"

  queryCondition:
    type: "sql"
    sql: |
      SELECT COUNT(*) as count, host
      FROM stream
      WHERE level = 'ERROR'
      GROUP BY host
      HAVING count > 10
    vrlFunction: |
      .processed_at = now()
      .alert_level = "critical"

  triggerCondition:
    frequency: 5
    frequencyType: "minutes"
    period: 15
    threshold: 10
    operator: ">="
    silence: 30
    timezone: "UTC"
    alignTime: true
    cron: ""

  destinations:
    - "Telegram_alert"

  deduplication:
    enabled: true
    fingerprintFields:
      - "_timestamp"
    timeWindowMinutes: 60

  rowTemplate: "Alert: {{level}} - {{message}}"
  rowTemplateType: "String"