# Example Alert with Aggregation and Having Clause
# This demonstrates the proper structure for aggregation-based alerts
apiVersion: openobserve.ai/v1alpha1
kind: OpenObserveAlert
metadata:
  name: aggregation-example
  namespace: o2operator
spec:
  configRef:
    name: openobserve-main       #dont forget to change this to your OpenObserveConfig
    namespace: o2operator

  name: "aggregation_with_having"
  description: "Example alert showing aggregation with having clause for filtering"
  streamName: "default"
  streamType: "logs"
  enabled: true

  queryCondition:
    type: "custom"

    # IMPORTANT: When using aggregation with a function,
    # include a having clause to filter the aggregated results
    aggregation:
      # Group results by these fields
      groupBy:
        - "host"
        - "service"

      # Aggregation function: count, sum, avg, min, max
      function: "count"

      # Having clause filters the aggregated results
      # This is RECOMMENDED when using aggregation functions
      having:
        column: "_count"     # Use _count for count function
        operator: ">="       # Comparison operator
        value: 10           # Threshold value
        ignoreCase: false   # For string comparisons

    # Optional: Pre-aggregation filters
    conditions: null
    # conditions:
    #   or:
    #     - column: job
    #       operator: ">"
    #       value: "11"
    #       ignore_case: false
    #     - or:
    #         - column: level
    #           operator: "="
    #           value: "111"
    #           ignore_case: true
    #         - column: log
    #           operator: "="
    #           value: "122"
    #           ignore_case: true

  triggerCondition:
    frequency: 5
    frequencyType: "minutes"
    period: 15
    threshold: 1     # Number of aggregated groups that exceed having condition
    operator: ">="
    silence: 30
    timezone: "UTC"

  deduplication:
    enabled: true
    fingerprintFields:
      - "host"
      - "service"
      - "error_code"
    timeWindowMinutes: 30

  destinations:
    - "test-o2-alerts"

  contextAttributes:
    - name: "priority"
      value: "P2"
      key: "priority"
    - name: "team"
      value: "platform"
      key: "team"

  rowTemplate: "Alert: {{service}} on {{host}} has {{_count}} errors in the last 15 minutes"
  rowTemplateType: "String"

---
# Example 2: Sum aggregation with having
apiVersion: openobserve.ai/v1alpha1
kind: OpenObserveAlert
metadata:
  name: high-response-time-sum
  namespace: o2operator
spec:
  configRef:
    name: openobserve-main
    namespace: o2operator

  name: "response_time_sum_alert"
  streamName: "default"
  streamType: "logs"

  queryCondition:
    type: "custom"
    aggregation:
      groupBy: ["endpoint", "method"]
      function: "sum"
      having:
        column: "duration_ms"  # Column being summed
        operator: ">"
        value: 10000          # Sum of durations > 10 seconds
        ignoreCase: false

  triggerCondition:
    frequency: 5
    frequencyType: "minutes"
    period: 10
    threshold: 1
    operator: ">="

  destinations:
    - "test-o2-alerts"

---
# Example 3: Average aggregation with having
apiVersion: openobserve.ai/v1alpha1
kind: OpenObserveAlert
metadata:
  name: high-avg-latency
  namespace: o2operator
spec:
  configRef:
    name: openobserve-main
    namespace: o2operator

  name: "average_latency_alert"
  streamName: "default"
  streamType: "logs"

  queryCondition:
    type: "custom"
    aggregation:
      groupBy: ["service", "region"]
      function: "avg"
      having:
        column: "latency"    # Column being averaged
        operator: ">="
        value: 500           # Avg latency >= 500ms
        ignoreCase: false

  triggerCondition:
    frequency: 2
    frequencyType: "minutes"
    period: 5
    threshold: 1
    operator: ">="

  destinations:
    - "test-o2-alerts"