apiVersion: openobserve.ai/v1alpha1
kind: OpenObserveAlert
metadata:
  name: alert1
  namespace: o2operator
spec:
  configRef:
    name: openobserve-main      #dont forget to change this to your OpenObserveConfig
    namespace: o2operator

  name: "alert_name_without_spaces"
  streamName: "default"
  streamType: "logs"
  enabled: true
  isRealTime: false
  description: "Alert description"
  folderName: "o2Alerts"

  queryCondition:
    type: "custom"

    aggregation: null
      # groupBy:
      #   - "field1"
      #   - "field2"
      # function: "count"
      # having:
      #   column: "_timestamp"
      #   operator: ">="
      #   value: 10
      #   ignoreCase: false

    conditions: null
    # conditions:
    #   or:
    #     - column: job
    #       operator: ">"
    #       value: "11"
    #       ignore_case: false
    #     - or:
    #         - column: level
    #           operator: "="
    #           value: "111"
    #           ignore_case: true
    #         - column: log
    #           operator: "="
    #           value: "122"
    #           ignore_case: true

    sql: ""
    promql: ""
    vrlFunction: ""

    multiTimeRange: []
      # - offset: "3h"
      # - offset: "6h"
      # - offset: "1d"

  triggerCondition:
    frequency: 5
    frequencyType: "minutes"
    period: 15
    threshold: 10
    operator: ">="
    silence: 30
    timezone: "UTC"
    alignTime: true
    cron: ""

  deduplication:
    enabled: false
    fingerprintFields:
      - "host"
      - "service"
    timeWindowMinutes: 60

  destinations:
    - "Telegram_alert"

  contextAttributes: []
    # - name: "environment"
    #   value: "production"
    #   key: "env"
    # - name: "team"
    #   value: "platform"
    #   key: "team_name"

  rowTemplate: "Alert: {{level}} - {{message}} on {{host}}"
  rowTemplateType: "String"