apiVersion: openobserve.ai/v1alpha1
kind: OpenObserveAlert
metadata:
  name: traces-alert
  namespace: o2operator
spec:
  configRef:
    name: openobserve-main       #dont forget to change this to your OpenObserveConfig
    namespace: o2operator

  name: "trace_error_alert"
  streamName: "default"
  streamType: "traces"

  queryCondition:
    type: "custom"
    conditions: null
    # conditions:
    #   or:
    #     - column: job
    #       operator: ">"
    #       value: "11"
    #       ignore_case: false
    #     - or:
    #         - column: level
    #           operator: "="
    #           value: "111"
    #           ignore_case: true
    #         - column: log
    #           operator: "="
    #           value: "122"
    #           ignore_case: true

  triggerCondition:
    frequency: 5
    frequencyType: "minutes"
    period: 15
    threshold: 10
    operator: ">="
    silence: 30
    timezone: "UTC"
    alignTime: true
    cron: ""

  destinations:
    - "test-o2-alerts"

  deduplication:
    enabled: true
    fingerprintFields:
      - "_timestamp"
    timeWindowMinutes: 60

  rowTemplate: "Alert: {{level}} - {{message}}"
  rowTemplateType: "String"