apiVersion: openobserve.ai/v1alpha1
kind: OpenObserveAlert
metadata:
  name: promql-metrics-alert
  namespace: o2operator
spec:
  configRef:
    name: openobserve-main       #dont forget to change this to your OpenObserveConfig
    namespace: o2operator

  name: "cpu_usage_alert"
  streamName: "cadvisor_version_info"
  streamType: "metrics"

  queryCondition:
    type: "promql"
    promql: |
      avg(rate(cpu_usage_seconds_total[5m])) by (instance) > 0.8

    conditions: null

  triggerCondition:
    frequency: 5
    frequencyType: "minutes"
    period: 15
    threshold: 10
    operator: ">="
    silence: 30
    timezone: "UTC"
    alignTime: true
    cron: ""

  destinations:
    - "test-o2-alerts"

  deduplication:
    enabled: true
    fingerprintFields:
      - "_timestamp"
    timeWindowMinutes: 60

  rowTemplate: "Alert: {{level}} - {{message}}"
  rowTemplateType: "String"