apiVersion: openobserve.ai/v1alpha1
kind: OpenObserveAlert
metadata:
  name: alert-with-dedup
  namespace: o2operator
spec:
  configRef:
    name: openobserve-main       #dont forget to change this to your OpenObserveConfig
    namespace: o2operator

  name: "dedup_alert"
  streamName: "default"
  streamType: "logs"

  queryCondition:
    type: "custom"
    aggregation:
      groupBy: ["host", "service"]
      function: "count"
      having:
        column: "_count"         # Column to evaluate (use _count for count function)
        operator: ">="          # Operators: =, !=, >, >=, <, <=
        value: 10               # Threshold value
        ignoreCase: false       # Case sensitivity (for string comparisons)
    conditions: null

  triggerCondition:
    frequency: 5
    frequencyType: "minutes"
    period: 15
    threshold: 10
    operator: ">="

  deduplication:
    enabled: true
    fingerprintFields:
      - "host"
      - "service"
      - "error_code"
    timeWindowMinutes: 30

  destinations:
    - "test-o2-alerts"

  contextAttributes:
    - name: "priority"
      value: "P2"
      key: "priority"