apiVersion: openobserve.ai/v1alpha1
kind: OpenObserveAlert
metadata:
  name: multi-time-range-alert
  namespace: o2operator
spec:
  configRef:
    name: openobserve-main       #dont forget to change this to your OpenObserveConfig
    namespace: o2operator

  name: "comparison_alert"
  streamName: "default"
  streamType: "logs"

  queryCondition:
    type: "custom"
    aggregation:
      groupBy: ["endpoint"]
      function: "avg"
      having:
        column: "response_time"
        operator: ">"
        value: 1000
    multiTimeRange:
      - offset: "1h"
      - offset: "3h"
      - offset: "6h"
      - offset: "12h"
      - offset: "1d"

  triggerCondition:
    frequency: 5
    frequencyType: "minutes"
    period: 15
    threshold: 10
    operator: ">="
    silence: 30
    timezone: "UTC"
    alignTime: true
    cron: ""

  destinations:
    - "test-o2-alerts"

  deduplication:
    enabled: true
    fingerprintFields:
      - "_timestamp"
    timeWindowMinutes: 60

  rowTemplate: "Alert: {{level}} - {{message}}"
  rowTemplateType: "String"