# ============================================================================
#                        OpenObserve Alert Template
#                        Alert Type: SQL (scheduled alert)
#                        Works for all streamType
# ============================================================================


apiVersion: openobserve.ai/v1alpha1
kind: OpenObserveAlert
metadata:
  name: scheduled-sql-metrics-alert  # Kubernetes resource name (lowercase, alphanumeric, hyphens)
  namespace: o2operator       # Target namespace for the alert resource
spec:
  configRef:
    name: openobserve-main         # Name of the OpenObserveConfig resource (Required)
    namespace: o2operator      # Namespace of the config (Optional, defaults to alert namespace)

  name: "scheduled-sql-metrics-alert"
  enabled: true
  description: ""
  streamName: "cpu_usage_seconds_total"
  streamType: "metrics"
  isRealTime: false
  folderName: "test_alerts"
  org: "dev"

  queryCondition:
    type: "sql"
    # aggregation: null
    # aggregation:
    #   groupBy:
    #     - "field1"
    #     - "field2"
    #   function: "count"
    #   having:
    #     column: "_count"         
    #     operator: ">="          
    #     value: 10              
    #     ignoreCase: false       
    # conditions: null
    # conditions:
    #   or:
    #     - column: job
    #       operator: ">"
    #       value: "11"
    #       ignore_case: false
    #     - or:
    #         - column: level
    #           operator: "="
    #           value: "111"
    #           ignore_case: true
    #         - column: log
    #           operator: "="
    #           value: "122"
    #           ignore_case: true
    # sql: ""
    sql: SELECT avg(value) as avg_value FROM "cpu_usage_seconds_total"
    # vrlFunction: ""
    # vrlFunction: |
    #   .processed_at = now()
    #   .alert_severity = if .error_count > 100 {
    #     "critical"
    #   } else if .error_count > 50 {
    #     "warning"
    #   } else {
    #     "info"
    #   }
    #   .needs_immediate_action = .error_count > 100

    # # promql: ""
    # promql: |
    #   # CPU usage above 80% for 5 minutes
    #   avg(rate(cpu_usage_seconds_total[5m])) by (instance) > 0.8

    #   # OR: Memory usage above 90%
    #   # (node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / node_memory_MemTotal_bytes > 0.9

    #   # OR: HTTP error rate above 1%
    #   # sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.01

    # multiTimeRange: []
    multiTimeRange:
      - offset: "30m"    
      - offset: "1h"    
      - offset: "3h"    
      - offset: "6h"     
      - offset: "1d"     
      - offset: "7d"     

  triggerCondition:
    frequency: 5
    frequencyType: "minutes"
    period: 15
    threshold: 10
    operator: ">="
    silence: 30
    timezone: "UTC"
    alignTime: true
    cron: ""
    toleranceInSecs: null

  deduplication:
    enabled: true
    fingerprintFields:
      - "host"           
      - "service"       
      - "error_code"     
    timeWindowMinutes: 60

  destinations:
    - "test-o2-alerts"      

  contextAttributes:
    - name: "environment"     
      value: "production"      
      key: "env"              
    - name: "team"
      value: "platform-engineering"
      key: "team_name"
    - name: "severity"
      value: "critical"
      key: "severity_level"
    - name: "sla"
      value: "99.99"
      key: "sla_percentage"
    - name: "cost_center"
      value: "engineering-123"
      key: "cost_center_id"

  rowTemplate: |
    Alert: {{level}} error detected
    Service: {{service}}
    Host: {{host}}
    Error Count: {{_count}}
    Environment: {{env}}
    Time: {{_timestamp}}
    Action: Check {{service}} logs on {{host}}

  rowTemplateType: "String"

  tzOffset: null
