# ============================================================================
#                 OpenObserve Destination Template
#                 Complete reference for all destination types
# ============================================================================
#
# Destinations in OpenObserve are divided into two categories:
# 1. Alert Destinations - Send alerts to external endpoints (require templates)
# 2. Pipeline Destinations - Send pipeline data to external systems (no templates)
#
# The category is automatically determined based on:
# - Alert: type is 'email', 'sns', OR type is 'http' with empty destinationTypeName
# - Pipeline: type is 'http' with non-empty destinationTypeName
#
# ============================================================================

apiVersion: openobserve.ai/v1alpha1
kind: OpenObserveDestination
metadata:
  name: destination-name          # Kubernetes resource name (lowercase, alphanumeric, hyphens)
  namespace: o2operator           # Target namespace (usually o2operator)
spec:
  # ============================================================================
  #                           REQUIRED FIELDS
  # ============================================================================

  # Reference to OpenObserveConfig resource
  configRef:
    name: openobserve-main       # Name of the OpenObserveConfig resource (Required)
    namespace: o2operator        # Namespace of the config (Optional, defaults to same namespace)

  # Destination configuration
  # Can be different from metadata.name
  name: destination-name         # Unique identifier in OpenObserve (Required)
                                
  # Destination type (Required)
  # Options: http and email
  type: http                     
                                

  # ============================================================================
  #                           OPTIONAL FIELDS
  # ============================================================================

  # Organization
  # Defaults to org from ConfigRef
  # Must exist in OpenObserve
  org: "default"                 # Organization name (Optional)
                               
                                

  # ============================================================================
  #                    ALERT DESTINATION FIELDS
  # ============================================================================
  # These fields are used when creating alert destinations

  # For ALL alert destinations (http, email)
  # Created using OpenObserveAlertTemplate resource
  template: alert-template-name  # Alert template name (Required for alerts)
                                
                                

  # For HTTP alert destinations
  # Template must exist in the same organization
  url: https://webhook.example.com/alerts   # Webhook URL (Required for http)
  method: post                              # HTTP method (Optional: post, put, get)
  headers:                                  # HTTP headers (Optional)
    Authorization: "Bearer TOKEN"
    Content-Type: "application/json"
  outputFormat: json                        # Output format (Optional: json, nestedevent)
  skipTlsVerify: false                      # Skip TLS verification (Optional, default: false)

  # For EMAIL alert destinations
  emails:                                   # Email addresses (Required for email)
    - alert@example.com
    - ops-team@example.com
  # Note: SMTP must be configured in OpenObserve

  # For SNS alert destinations (AWS Simple Notification Service)
  actionId: "sns-action-123"                # SNS Action ID (Optional)
  awsRegion: us-east-1                      # AWS Region (Required for sns)
  snsTopicArn: arn:aws:sns:us-east-1:123456789012:MyTopic  # SNS Topic ARN (Required)

  # ============================================================================
  #                    PIPELINE DESTINATION FIELDS
  # ============================================================================
  # These fields are used when creating pipeline destinations
  # Options: custom, openobserve, splunk, newrelic,  elasticsearch, dynatrace, datadog
  destinationTypeName: custom    # Pipeline destination type (Required for pipelines)


  # URL is required for all pipeline destinations
  url: https://api.example.com/ingest

  # Headers vary by destination type:
  # - Splunk: Authorization: "Splunk YOUR-HEC-TOKEN"
  # - Datadog: DD-API-KEY: "YOUR-API-KEY"
  # - Dynatrace: Authorization: "Api-Token YOUR-TOKEN"
  # - NewRelic: Api-Key: "YOUR-API-KEY"
  # - OpenObserve: Authorization: "Basic BASE64_ENCODED"
  # - Custom: Any headers you need

  # Metadata for pipeline destinations (Optional but recommended)
  metadata:
    # For Datadog (ddsource and ddtags are MANDATORY):
    ddsource: "openobserve"
    ddtags: "env:production,service:logs"

    # For Splunk (Optional but recommended):
    hostname: "production-server"
    source: "openobserve"
    sourcetype: "openobserve_logs"

    # For Custom destinations (any key-value pairs):
    environment: "production"
    datacenter: "us-east-1"

  # Output Format Requirements by destination type:
  # - openobserve: MUST be "json"
  # - splunk: MUST be "nestedevent"
  # - newrelic: MUST be "json"
  # - elasticsearch: MUST be "esbulk" or object with esbulk.index
  # - dynatrace: MUST be "json"
  # - datadog: MUST be "json"
  # - custom: Can be "json" or "nestedevent"

  outputFormat: json  # For most destinations

  # For Elasticsearch, outputFormat can also be an object:
  # outputFormat:
  #   esbulk:
  #     index: "openobserve-logs"


# ============================================================================
#                        VALIDATION RULES
# ============================================================================
#
# The webhook validator enforces:
#
# 1. Organization must exist and be accessible
# 2. Alert destinations MUST have a template that exists in the same org
# 3. Pipeline destinations MUST NOT have a template
# 4. Output format must match destination type requirements
# 5. Required headers must be present for specific destination types
# 6. For Datadog: metadata must include ddsource and ddtags
# 7. URL format must be valid
# 8. Email addresses must be valid format
# 9. Destination names must be unique within an organization

# ============================================================================
#                        COMMON EXAMPLES
# ============================================================================

# --- HTTP Alert Destination ---
# apiVersion: openobserve.ai/v1alpha1
# kind: OpenObserveDestination
# metadata:
#   name: slack-alerts
#   namespace: o2operator
# spec:
#   configRef:
#     name: openobserve-main
#   name: slack-critical-alerts
#   type: http
#   url: https://hooks.slack.com/services/YOUR/WEBHOOK/URL
#   template: critical-alert-template
#   outputFormat: json

# --- Email Alert Destination ---
# apiVersion: openobserve.ai/v1alpha1
# kind: OpenObserveDestination
# metadata:
#   name: email-alerts
#   namespace: o2operator
# spec:
#   configRef:
#     name: openobserve-main
#   name: ops-team-emails
#   type: email
#   emails:
#     - ops@example.com
#     - alerts@example.com
#   template: email-alert-template

# --- Splunk Pipeline Destination ---
# apiVersion: openobserve.ai/v1alpha1
# kind: OpenObserveDestination
# metadata:
#   name: splunk-logs
#   namespace: o2operator
# spec:
#   configRef:
#     name: openobserve-main
#   name: splunk-hec-logs
#   type: http
#   destinationTypeName: splunk
#   url: https://splunk.example.com:8088/services/collector/event
#   headers:
#     Authorization: "Splunk YOUR-HEC-TOKEN"
#   metadata:
#     source: "openobserve"
#     sourcetype: "json"
#   outputFormat: nestedevent

# --- Datadog Pipeline Destination ---
# apiVersion: openobserve.ai/v1alpha1
# kind: OpenObserveDestination
# metadata:
#   name: datadog-logs
#   namespace: o2operator
# spec:
#   configRef:
#     name: openobserve-main
#   name: datadog-pipeline
#   type: http
#   destinationTypeName: datadog
#   url: https://http-intake.logs.datadoghq.com/api/v2/logs
#   headers:
#     DD-API-KEY: "YOUR-API-KEY"
#   metadata:
#     ddsource: "openobserve"    # MANDATORY
#     ddtags: "env:prod,service:logs"  # MANDATORY
#   outputFormat: json

# ============================================================================
#                        TROUBLESHOOTING
# ============================================================================
#
# Common errors and solutions:
#
# 1. "Organization 'X' does not exist"
#    - Verify org exists: kubectl get openobserveconfig -o yaml
#    - Check available orgs in OpenObserve UI
#
# 2. "Alert template 'Y' does not exist in organization 'X'"
#    - Create template first: kubectl apply -f alert-template.yaml
#    - Verify template exists: kubectl get openobservealerttemplates
#
# 3. "outputFormat must be 'Z'"
#    - Check the output format requirements for your destination type
#    - See the Output Format Requirements section above
#
# 4. "Email destinations require SMTP to be configured"
#    - Configure SMTP in OpenObserve settings
#    - Contact your OpenObserve administrator
#
# 5. "Datadog destination requires metadata with 'ddsource' and 'ddtags'"
#    - Add required metadata fields as shown in examples
#
# 6. "Destination with name 'X' already exists"
#    - Use a different name or delete the existing destination
#    - Check: kubectl get openobservedestinations
#
# To view detailed error messages:
# kubectl describe openobservedestination <name> -n o2operator
#
# To check operator logs:
# kubectl logs -n o2operator -l app=openobserve-operator --tail=50
#
# ============================================================================