# ============================================================================
#                  OpenObserve PromQL Query Pipeline Test Template 
#                       Connect Source -> Destination
# ============================================================================

apiVersion: openobserve.ai/v1alpha1
kind: OpenObservePipeline
metadata:
  name: promql-query-pipeline1  # Kubernetes resource name (lowercase, alphanumeric, hyphens)
  namespace: o2operator           # Target namespace for the pipeline resource
spec:
  configRef:
    name: openobserve-main         # Name of the OpenObserveConfig resource (Required)
    namespace: o2operator      # Namespace of the config (Optional, defaults to pipeline namespace)

  # ============================================================================
  # PIPELINE IDENTIFICATION & BASIC SETTINGS
  # ============================================================================

  # Pipeline name in OpenObserve (Required)
  # - Must be unique within the organization
  # - This is the internal name in OpenObserve, different from K8s resource name
  # - Pattern: alphanumeric with underscores/hyphens
  # - Example: "log_enrichment_pipeline", "metrics_aggregation"
  name: "promql-query-pipeline1"

  # Pipeline description (Optional but recommended)
  # - Human-readable description of pipeline purpose
  # - Max length: 500 characters
  # - Should explain: what data it processes, transformations applied, output
  description: "Test Pipeline"

  # Enable/disable the pipeline (Optional, defaults to true)
  # - When false, pipeline won't process data but remains configured
  # - Useful for temporarily disabling pipelines during maintenance
  enabled: true

  # Organization name (Optional)
  # - Usually auto-determined from configRef
  # - Override only if targeting different org
  org: "default"

  # ============================================================================
  # DATA SOURCE CONFIGURATION (Required)
  # Defines the input stream for the pipeline
  # ============================================================================
  # Source configuration for scheduled pipeline with query
  # This is a scheduled pipeline that runs on a schedule with a PromQL query
  source:
    # streamName is not required for scheduled pipelines with query conditions
    sourceType: "scheduled"   # from source.source_type
    streamType: "metrics"     # from source.stream_type
    queryCondition:
      type: "promql"
      promql: "cadvisor_version_info{}"
      promqlCondition:
        column: "value"
        operator: ">="
        value: 0
        ignoreCase: false
      searchEventType: "derivedstream"
    triggerCondition:
      period: 10
      operator: "="
      threshold: 0
      frequency: 10
      frequencyType: "minutes"
      silence: 0
      timezone: "UTC"
      alignTime: true

  # ============================================================================
  # PIPELINE NODES (Required)
  # Define processing steps - minimum 1 node required
  # ============================================================================
  nodes:
    # ==================================
    # NODE TYPE: STREAM OUTPUT NODE
    # Routes data to another stream
    # ==================================
    - id: "output-errors"
      type: "stream"
      name: "Route to Error Stream"

      config:
        org_id: "default"           # Target organization
        stream_name: "error_logs"   # Target stream name
        stream_type: "logs"         # Target stream type

  # ============================================================================
  # PIPELINE EDGES (Optional but usually required)
  # Define connections between nodes to create data flow
  # ============================================================================
  edges: []
  
  # Note: For realtime pipelines, edges from source to first nodes
  # are automatically created if not specified
