apiVersion: openobserve.ai/v1alpha1
kind: OpenObservePipeline
metadata:
  name: query-src-to-dest-test
  namespace: o2operator
spec:
  # Reference to OpenObserveConfig
  configRef:
    name: openobserve-main       #dont forget to change this to your OpenObserveConfig
    namespace: o2operator

  # Pipeline metadata - matching the JSON
  name: "query-src-to-dest-test"
  description: ""
  enabled: true

  # Organization (from JSON)
  org: "default"

  # Pipeline ID from JSON (optional)
  # pipeline_id: "7400589693177298944"

  # Source configuration for scheduled pipeline with query
  # This is a scheduled pipeline that runs on a schedule with a PromQL query
  source:
    # streamName is not required for scheduled pipelines with query conditions
    sourceType: "scheduled"   # from source.source_type
    streamType: "metrics"     # from source.stream_type
    queryCondition:
      type: "promql"
      promql: "cadvisor_version_info{}"
      promqlCondition:
        column: "value"
        operator: ">="
        value: 0
        ignoreCase: false
      searchEventType: "derivedstream"
    triggerCondition:
      period: 1
      operator: "="
      threshold: 0
      frequency: 1
      frequencyType: "minutes"
      silence: 0
      timezone: "UTC"
      alignTime: true

  # Processing nodes
  # Note: The scheduled query source is handled above
  # We only define the output node here
  nodes:
    # Output node from JSON (id: 888b058b-6740-440d-929a-2f09790340e2)
    - id: "output-stream"
      type: "stream"           # from data.node_type
      name: "Output Stream"
      config:
        stream_name: "default"  # from data.stream_name
        stream_type: "logs"     # from data.stream_type

  # Edges - for simple pipeline, connection is implicit
  edges: []  # Empty because it's a direct source->output connection

# ---
# # Alternative approach if the operator doesn't support query conditions in source
# # Use a query node instead
# apiVersion: openobserve.ai/v1alpha1
# kind: OpenObservePipeline
# metadata:
#   name: testpipelinesourcenodequery-alt
#   namespace: o2operator
# spec:
#   configRef:
#     name: openobserve-main
#     namespace: o2operator

#   name: "testpipelinesourcenodequery-alt"
#   description: "Alternative using query node"
#   enabled: true
#   org: "default"

#   # Simple metrics source
#   source:
#     streamName: "_all"         # Use a catch-all or specific metric stream
#     streamType: "metrics"
#     sourceType: "realtime"     # Process in realtime

#   # Processing nodes
#   nodes:
#     # Query node to filter metrics
#     - id: "query-filter"
#       type: "query"
#       name: "Filter Metrics"
#       config:
#         # Convert PromQL to SQL-like query
#         query: |
#           SELECT *
#           FROM stream
#           WHERE __name__ = 'cadvisor_version_info'
#             AND value >= 0
#         query_type: "sql"

#     # Output to logs stream
#     - id: "output-stream"
#       type: "stream"
#       name: "Output Stream"
#       config:
#         stream_name: "default"
#         stream_type: "logs"

#   # Define edges
#   edges:
#     - source: "query-filter"
#       target: "output-stream"